apiVersion: v1
# crea un servicio
kind: Service
metadata:
  name: posts-srv
spec:
  # crea un servicio del tipo nodePort
  type: NodePort
  selector:
    # busca todos pods/apps que tenga la label posts
    app: posts
  ports:
    - name: posts
      protocol: TCP
      # porto del servicio
      port: 4000
      # porto del Pod
      targetPort: 4000
